// apps/bot/frontend/components/shared/form/Select.tsx
import { Fragment, useEffect, useState } from 'react'
import { Listbox, Transition } from '@headlessui/react'
import { SelectOption } from '../../../shared/helpers/form/select-option'
import { CheckIcon, ChevronUpDownIcon } from '@heroicons/react/20/solid'
import Image from 'next/image'
import Picture from '../image/Picture'

interface ComponentProps {
  options: SelectOption[]
  onChange?: (selected: SelectOption) => void,
  selected?: any
}

export default function Select(props: ComponentProps) {
  const { options, onChange, selected } = props
  const [selectedOption, setSelectedOption] = useState(options[0])

  useEffect(() => {
    const option = options.filter(option => option.value == selected).shift()

    if (option) {
      setSelectedOption(option)
    }
  }, [selected])

  const onChangeSelectedOption = (option: SelectOption) => {
    setSelectedOption(option)

    if (onChange) {
      onChange(option)
    }
  }

  return (
    <div className="w-72">
      <Listbox value={selectedOption} onChange={onChangeSelectedOption}>
        <div className="relative mt-1">
          <Listbox.Button className="relative w-full cursor-default rounded-lg bg-white py-2 pl-10 pr-10 text-left shadow-md focus:outline-none focus-visible:border-indigo-500 focus-visible:ring-2 focus-visible:ring-white focus-visible:ring-opacity-75 focus-visible:ring-offset-2 focus-visible:ring-offset-orange-300 sm:text-sm">
            {selectedOption.labelIcon ? (
              <span className="absolute inset-y-0 left-0 flex items-center pl-3">
                <Picture
                  src={selectedOption.labelIcon}
                  className="h-5 w-5 rounded-full"
                  alt={`Icon of ${selectedOption.label} option`}
                />
              </span>
            ) : null}
            <span className="block truncate">{selectedOption.label}</span>
            <span className="pointer-events-none absolute inset-y-0 right-0 flex items-center pr-2">
              <ChevronUpDownIcon
                className="h-5 w-5 text-gray-400"
                aria-hidden="true"
              />
            </span>
          </Listbox.Button>
          <Transition
            as={Fragment}
            leave="transition ease-in duration-100"
            leaveFrom="opacity-100"
            leaveTo="opacity-0"
          >
            <Listbox.Options className="z-10 absolute mt-1 max-h-60 w-full overflow-auto rounded-md bg-white py-1 text-base shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none sm:text-sm">
              {options.map((option, index) => (
                <Listbox.Option
                  key={index}
                  value={option}
                  disabled={option.disabled}
                  className={({ active }) =>
                    `relative cursor-default select-none py-2  pr-10
                    ${ option.labelIcon ? 'pl-10' : 'pl-4' }
                    ${ active ? 'bg-primary' : 'text-gray-900'}`
                  }
                >
                  {({ selected }) => (
                    <>
                      {option.labelIcon ? (
                        <span className="absolute inset-y-0 left-0 flex items-center pl-3">
                          <Picture
                            src={option.labelIcon}
                            className="h-5 w-5 rounded-full"
                            alt={`Icon of ${option.label} option`}
                          />
                        </span>
                      ) : null}
                      <span
                        className={`block truncate ${
                          selected ? 'font-medium' : 'font-normal'
                        }`}
                      >
                        {option.label}
                      </span>
                      {selected ? (
                        <span className="absolute inset-y-0 right-0 flex items-center pr-3 text-gray-900">
                          <CheckIcon className="h-5 w-5" aria-hidden="true" />
                        </span>
                      ) : null}
                    </>
                  )}
                </Listbox.Option>
              ))}
            </Listbox.Options>
          </Transition>
        </div>
      </Listbox>
    </div>
  )
}

// frontend/components/form/Select.vue
<template>
  <Listbox as="div" v-model="selected">
    <ListboxLabel class="block text-sm font-medium text-gray-700">{{ props.label }}</ListboxLabel>
    <div class="relative mt-1">
      <ListboxButton class="relative w-full cursor-default rounded-md border border-gray-300 bg-white py-2 pl-3 pr-10 text-left shadow-sm focus:border-indigo-500 focus:outline-none focus:ring-1 focus:ring-indigo-500 sm:text-sm">
        <span class="flex items-center">
          <img v-if="selected.labelIcon" :src="selected.labelIcon" alt="" class="h-6 w-6 flex-shrink-0 rounded-full" />
          <span class="ml-3 block truncate">{{ selected.label }}</span>
        </span>
        <span class="pointer-events-none absolute inset-y-0 right-0 ml-3 flex items-center pr-2">
          <ChevronUpDownIcon class="h-5 w-5 text-gray-400" aria-hidden="true" />
        </span>
      </ListboxButton>

      <transition leave-active-class="transition ease-in duration-100" leave-from-class="opacity-100" leave-to-class="opacity-0">
        <ListboxOptions class="absolute z-10 mt-1 max-h-56 w-full overflow-auto rounded-md bg-white py-1 text-base shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none sm:text-sm">
          <ListboxOption as="template" v-for="option in options" :key="option.label" :value="option" v-slot="{ active, selected }">
            <li :class="[active ? 'text-white bg-indigo-600' : 'text-gray-900', 'relative cursor-default select-none py-2 pl-3 pr-9']">
              <div class="flex items-center">
                <img v-if="option.labelIcon" :src="option.labelIcon" alt="" class="h-6 w-6 flex-shrink-0 rounded-full" />
                <span :class="[selected ? 'font-semibold' : 'font-normal', 'ml-3 block truncate']">{{ option.label }}</span>
              </div>

              <span v-if="selected" :class="[active ? 'text-white' : 'text-indigo-600', 'absolute inset-y-0 right-0 flex items-center pr-4']">
                <CheckIcon class="h-5 w-5" aria-hidden="true" />
              </span>
            </li>
          </ListboxOption>
        </ListboxOptions>
      </transition>
    </div>
  </Listbox>
</template>

<script setup lang="ts">
import { Listbox, ListboxButton, ListboxLabel, ListboxOptions, ListboxOption } from '@headlessui/vue'
import { CheckIcon, ChevronUpDownIcon } from '@heroicons/vue/20/solid'
import { Option } from "~/modules/shared/form/select";

interface ComponentProps {
  label: string;
  options: Option[];
  modelValue?: Option;
}

const emit = defineEmits(['update:modelValue'])
const props = defineProps<ComponentProps>()

const { options, modelValue } = props
const selected = ref(modelValue)

watch(selected, (newValue) => emit('update:modelValue', newValue))
</script>
